services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.3
    command: "start-dev --import-realm"
#    command: "start-dev"
    restart: on-failure
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./identity/realm-export.json:/opt/keycloak/data/import/realm-export.json
    networks:
      - social-media-network

networks:
  social-media-network:
    driver: bridge
    name: social-media-network